spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/users
    username: user
    password: user
  kafka:
    bootstrap-servers:
      - localhost:9092
    template:
      default-topic: report-topic
server:
  port: 8081