jwt:
  secret: ${JWT_SECRET}
  lifetime: ${JWT_LIFETIME}

spring:
  datasource:
    url: jdbc:postgresql://users-db:5432/users
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  flyway:
    schemas:
      - public
      - user_management
      - task_management