jwt:
  secret: 82cb78fbdb725dbef6fb6b64a94727ec9dc78c3e153c91b5aa6cd35b58f0be9e
  lifetime: 10m

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/users
    username: user
    password: user
  flyway:
    schemas:
      - public
      - user_management
      - task_management